package com.rhpam.banking;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer income;
	private java.lang.String govtId;
	private java.lang.Integer phoneNumber;

	private java.time.LocalDate dateOfBirth;

	public Applicant() {
	}

	public java.lang.Integer getIncome() {
		return this.income;
	}

	public void setIncome(java.lang.Integer income) {
		this.income = income;
	}

	public java.lang.String getGovtId() {
		return this.govtId;
	}

	public void setGovtId(java.lang.String govtId) {
		this.govtId = govtId;
	}

	public java.lang.Integer getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.time.LocalDate getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.time.LocalDate dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Applicant(java.lang.Integer income, java.lang.String govtId,
			java.lang.Integer phoneNumber, java.time.LocalDate dateOfBirth) {
		this.income = income;
		this.govtId = govtId;
		this.phoneNumber = phoneNumber;
		this.dateOfBirth = dateOfBirth;
	}

}